name 'abstractit-postfix'
author 'abstractit'
version '0.1.2'
summary 'manage a postfix server'
description "manage postfix server with puppet"
project_page 'https://github.com/abstractitptyltd/puppet-postfix'
source 'https://github.com/abstractitptyltd/puppet-postfix'
license 'Apache v2 Licence'
dependency 'puppetlabs/stdlib', '>=3.2.1'
dependency 'puppetlabs/concat', '>=1.0.2'
